CarInsurance/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarInsurance.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CarInsurance/Controllers/InsureeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CarInsurance.Models;

namespace CarInsurance.Controllers
{
    public class InsureeController : Controller
    {
        private InsuranceEntities db = new InsuranceEntities();

        private int CalculateQuote(Insuree insuree)
        {
            int baseRate = 50;

            // Age calculation
            var age = DateTime.Today.Year - insuree.DateOfBirth.Year;
            if (age <= 18)
            {
                baseRate += 100;
            }
            else if (age > 18 && age <= 25)
            {
                baseRate += 50;
            }
            else
            {
                baseRate += 25;
            }

            // Car year calculation
            if (insuree.CarYear < 2000 || insuree.CarYear > 2015)
            {
                baseRate += 25;
            }

            // Car make and model calculation
            if (insuree.CarMake.Equals("Porsche", StringComparison.OrdinalIgnoreCase))
            {
                baseRate += 25;
                if (insuree.CarModel.Equals("911 Carrera", StringComparison.OrdinalIgnoreCase))
                {
                    baseRate += 25;
                }
            }

            // Speeding tickets
            baseRate += insuree.SpeedingTickets * 10;

            // DUI check
            if (insuree.DUI)
            {
                baseRate = (int)(baseRate * 1.25);
            }

            // Full coverage check
            if (insuree.CoverageType) // Assuming CoverageType is a boolean
            {
                baseRate = (int)(baseRate * 1.5);
            }

            return baseRate;
        }


        // GET: Insuree
        public ActionResult Index()
        {
            return View(db.Insurees.ToList());
        }

        // GET: Insuree/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Insuree insuree = db.Insurees.Find(id);
            if (insuree == null)
            {
                return HttpNotFound();
            }
            return View(insuree);
        }

        // GET: Insuree/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Insuree/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FirstName,LastName,EmailAddress,DateOfBirth,CarYear,CarMake,CarModel,DUI,SpeedingTickets,CoverageType,Quote")] Insuree insuree)
        {
            if (ModelState.IsValid)
            {
                insuree.Quote = CalculateQuote(insuree);
                db.Insurees.Add(insuree);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = insuree.Id });
            }

            return View(insuree);
        }

        public ActionResult QuoteResult(int id)
        {
            var insuree = db.Insurees.Find(id);
            if (insuree == null)
            {
                return HttpNotFound();
            }
            return View(insuree);
        }

        // GET: Insuree/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Insuree insuree = db.Insurees.Find(id);
            if (insuree == null)
            {
                return HttpNotFound();
            }
            return View(insuree);
        }

        // POST: Insuree/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,EmailAddress,DateOfBirth,CarYear,CarMake,CarModel,DUI,SpeedingTickets,CoverageType,Quote")] Insuree insuree)
        {
            if (ModelState.IsValid)
            {
                // Recalculate the quote before saving changes
                insuree.Quote = CalculateQuote(insuree);

                db.Entry(insuree).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(insuree);
        }

        // GET: Insuree/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Insuree insuree = db.Insurees.Find(id);
            if (insuree == null)
            {
                return HttpNotFound();
            }
            return View(insuree);
        }

        // POST: Insuree/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Insuree insuree = db.Insurees.Find(id);
            db.Insurees.Remove(insuree);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Admin()
        {
            if (Session["IsAdmin"] as bool? != true)
            {
                return RedirectToAction("Index", "Home"); 
            }

            var insurees = db.Insurees.ToList();
            return View(insurees);
        }

        public ActionResult AdminLogin(string username, string password)
        {
            if (username == "admin" && password == "admin")
            {
                Session["IsAdmin"] = true;
                return RedirectToAction("Admin");
            }
            else
            {
                TempData["AdminLoginError"] = "Invalid username or password.";
                return RedirectToAction("Index", "Home"); // Redirect back to home on failure
            }
        }
    }

    
}

CarInsurance/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CarInsurance/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CarInsurance/Views/Home/Index.cshtml
@model CarInsurance.Models.Insuree
@using CarInsurance.Models

@{ ViewBag.Title = "Home Page"; }

<div class="jumbotron">
    <h1>Welcome to Our Car Insurance Application</h1>
    <p class="lead">Get a quick and easy quote for your car insurance.</p>
</div>

<!-- Form for Insurance Quote -->
@using (Html.BeginForm("Create", "Insuree", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.FirstName)
        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName)
        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EmailAddress)
        @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DateOfBirth)
        @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control", type = "date" } })
        @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CarYear)
        @Html.EditorFor(model => model.CarYear, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.CarYear, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CarMake)
        @Html.EditorFor(model => model.CarMake, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.CarMake, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CarModel)
        @Html.EditorFor(model => model.CarModel, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.CarModel, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DUI)
        @Html.EditorFor(model => model.DUI, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.DUI, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SpeedingTickets)
        @Html.EditorFor(model => model.SpeedingTickets, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.SpeedingTickets, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CoverageType)
        <div>
            @Html.RadioButtonFor(model => model.CoverageType, true) Full Coverage
            @Html.RadioButtonFor(model => model.CoverageType, false) Liability Only
        </div>
        @Html.ValidationMessageFor(model => model.CoverageType, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <input type="submit" value="Get Quote" class="btn btn-primary" />
    </div>
}


<div>
    <h2>Admin Login</h2>
    @using (Html.BeginForm("AdminLogin", "Insuree", FormMethod.Post))
    {
        <div class="form-group">
            <label>Username</label>
            <input type="text" name="username" class="form-control" />
        </div>
        <div class="form-group">
            <label>Password</label>
            <input type="password" name="password" class="form-control" />
        </div>
        <input type="submit" value="Login" class="btn btn-default" />


    }
</div>